=== ProteinsWebTeam/Pfam/trunk/PfamWeb/root/static/documents/pfamDomainGraphics.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd"
    targetNamespace="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.1">
    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sequence" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="format" default="png">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="png"/>
                        <xs:enumeration value="jpg"/>
                        <xs:enumeration value="gif"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="layout" default="continuous">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="continuous"/>
                        <xs:enumeration value="dicontinuous"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="scale_x" type="xs:float" default="1.0"/>
            <xs:attribute name="scale_y" type="xs:float" default="1.0"/>
            
        </xs:complexType>
    </xs:element>
    
    <xs:element name="sequence">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="region" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="markup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="length" type="xs:integer"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="display_data" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="region">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="colour1" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="colour"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="colour2" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="colour"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:choice>
                    <xs:element name="bigShape">
                        <xs:complexType>
                            <xs:attribute name="leftStyle" default="curved">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="straight"/>
                                        <xs:enumeration value="jagged"/>
                                        <xs:enumeration value="curved"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="rightStyle" default="curved">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="straight"/>
                                        <xs:enumeration value="jagged"/>
                                        <xs:enumeration value="curved"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="medShape"/>
                    <xs:element name="smlShape"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="start" type="xs:integer"/>
            <xs:attribute name="end" type="xs:integer"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="link_URL" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="colour">
        <xs:complexType>
            <xs:choice>
                <xs:element name="hex">
                    <xs:complexType>
                        <xs:attribute name="hexcode" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="RGB">
                    <xs:complexType>
                        <xs:attribute name="R" type="xs:integer"/>
                        <xs:attribute name="G" type="xs:integer"/>
                        <xs:attribute name="B" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="markup">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="line" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="colour"/>
                        </xs:sequence>
                        <xs:attribute name="style" default="bold">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="bold"/>
                                    <xs:enumeration value="dashed"/>
				    <xs:enumeration value="mixed"/>	
				    <xs:enumeration value="straight"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="head" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="colour"/>
                        </xs:sequence>
                        <xs:attribute name="style" default="diamond">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="circle"/>
                                    <xs:enumeration value="square"/>
			            <xs:enumeration value="diamond"/>
			            <xs:enumeration value="arrow"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="start" type="xs:integer"/>
            <xs:attribute name="end" type="xs:integer"/>
            <xs:attribute name="label" type="xs:string"/>    
            <xs:attribute name="v_align" default="bottom">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="bottom"/>
                        <xs:enumeration value="top"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ProteinsWebTeam/Pfam/trunk/PfamWeb/root/static/images/help/lollipop.xml
<?xml version="1.0" encoding="UTF-8"?>
<image xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" format="png" layout="continuous" scale_x="0.5" scale_y="1.0">
    <sequence length="200" name="Lollipop">
	    	<markup start="20" v_align="top" label="bold line, Square head">
            <line style="bold">
                <colour>
                    <hex hexcode="666666"/>
                </colour>
            </line>
            <head style="square">
                <colour>
                    <hex hexcode="FF3366"/>
                </colour>
            </head>
        </markup>
        <markup start="40" v_align="bottom" label="bold line, Square head">
            <line style="dashed">
                <colour>
                    <hex hexcode="666666"/>
                </colour>
            </line>
            <head style="square">
                <colour>
                    <hex hexcode="9966cc"/>
                </colour>
            </head>
        </markup>
        <markup start="80" v_align="bottom" label="bold line, Diamond head">
            <line style="bold line">
                <colour>
                    <hex hexcode="666666"/>
                </colour>
            </line>
            <head style="diamond">
                <colour>
                    <hex hexcode="FF3366"/>
                </colour>
            </head>
        </markup>
        <markup start="120" v_align="bottom" label="dashed line, Circle head">
            <line style="dashed">
                <colour>
                    <hex hexcode="666666"/>
                </colour>
            </line>
            <head style="circle">
                <colour>
                    <hex hexcode="333399"/>
                </colour>
            </head>
        </markup>
	      <markup start="60" v_align="top" label="bold line, Square head">
            <line style="bold">
                <colour>
                    <hex hexcode="666666"/>
                </colour>
            </line>
            <head style="square">
                <colour>
                    <hex hexcode="66ff00"/>
                </colour>
            </head>
        </markup>
        <markup start="100" v_align="top" label="bold line, Diamond head">
            <line style="bold line">
                <colour>
                    <hex hexcode="666666"/>
                </colour>
            </line>
            <head style="diamond">
                <colour>
                    <hex hexcode="FF3366"/>
                </colour>
            </head>
        </markup>
        <markup start="140" v_align="top" label="dashed line, Circle head">
            <line style="dashed">
                <colour>
                    <hex hexcode="666666"/>
                </colour>
            </line>
            <head style="circle">
                <colour>
                    <hex hexcode="cc9933"/>
                </colour>
            </head>
        </markup>      
    </sequence>
</image>

=== ProteinsWebTeam/Pfam/trunk/PfamWeb/root/static/images/help/disulphideActiveSite.xml
<?xml version="1.0"?>
<image xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" layout="continuous" format="png" scale_x="0.5" scale_y="1">
  <sequence name="ActiveSite" length="400">

    <region start="48" end="104" label="Inhibitor_I29">
      <colour1>
        <colour>
          <hex hexcode="1fc01f"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="47e847"/>
        </colour>
      </colour2>
      <bigShape leftStyle="curved" rightStyle="curved"/>
    </region>
    <region start="134" end="343" label="Peptidase_C1">
      <colour1>
        <colour>
          <hex hexcode="c00f0f"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="e83737"/>
        </colour>
      </colour2>
      <bigShape leftStyle="curved" rightStyle="curved"/>
    </region>
    <region start="1" end="26" label="Signal Peptide" >
      <colour1>
        <colour>
          <hex hexcode="FF9C00"/>
        </colour>
      </colour1>
      <smlShape/>
    </region>
    <markup start="155" end="196" v_align="top" label="Disulphide, 155-196">
      <line style="bold">
        <colour>
          <hex hexcode="333333"/>
        </colour>
      </line>
    </markup>
    <markup start="189" end="228" v_align="top" label="Disulphide, 189-228">
      <line style="bold">
        <colour>
          <hex hexcode="333333"/>
        </colour>
      </line>
    </markup>
    <markup start="286" end="333" v_align="top" label="Disulphide, 286-333">
      <line style="bold">
        <colour>
          <hex hexcode="333333"/>
        </colour>
      </line>
    </markup>
    <markup start="158" v_align="bottom" label="Active site, C158">
      <line style="bold">
        <colour>
          <hex hexcode="333333"/>
        </colour>
      </line>
      <head style="diamond">
        <colour>
          <hex hexcode="FF3366"/>
        </colour>
      </head>
    </markup>
    <markup start="292" v_align="bottom" label="Pfam predicted active site, H292">
      <line style="bold">
        <colour>
          <hex hexcode="333333"/>
        </colour>
      </line>
      <head style="diamond">
        <colour>
          <hex hexcode="9900CC"/>
        </colour>
      </head>
    </markup>
    <markup start="308" v_align="bottom" label="SwissProt predicted active site, N308">
      <line style="bold">
        <colour>
          <hex hexcode="333333"/>
        </colour>
      </line>
      <head style="diamond">
        <colour>
          <hex hexcode="FF66FF"/>
        </colour>
      </head>
    </markup>
  </sequence>
</image>

=== ProteinsWebTeam/Pfam/trunk/iPfamWeb/root/static/images/help/pfamB.xml
<?xml version="1.0"?>
<image xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" layout="continuous" format="png" scale_x="0.5" scale_y="1">
  <sequence name="PfamB" length="200" >
    <region start="8" end="68" label="Pfam-B_39520" link_URL="/cgi-bin/Pfam/pfambget.pl?acc=PB039520">
      <colour1>
        <colour>
          <hex hexcode="bdc000~d1d414~e5e828~c008ae~00bac0~00a6ac~00888e"/>
        </colour>
      </colour1>
      <smlShape/>
    </region>
    <region start="105" end="176" label="Pfam-B_43847" link_URL="/cgi-bin/Pfam/pfambget.pl?acc=PB043847">
      <colour1>
        <colour>
          <hex hexcode="8484c0~9898d4~acace8~93c090~c0af92~ac9b7e~8e7d60"/>
        </colour>
      </colour1>
      <smlShape/>
    </region>
  </sequence>
</image>

=== ProteinsWebTeam/Pfam/trunk/iPfamWeb/root/static/images/help/context.xml
<?xml version="1.0"?>
<image xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" layout="continuous" format="png" scale_x="0.5" scale_y="1">
  <sequence name="context" length="200" >
    <region start="82" end="118" label="HEAT" >
      <colour1>
        <colour>
          <hex hexcode="1fc01f"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="47e847"/>
        </colour>
      </colour2>
      <bigShape leftStyle="straight" rightStyle="straight"/>
    </region>
    <region start="159" end="195" label="HEAT" >
      <colour1>
        <colour>
          <hex hexcode="1fc01f"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="47e847"/>
        </colour>
      </colour2>
      <bigShape leftStyle="straight" rightStyle="straight"/>
    </region>
		<region start="120" end="155" label="HEAT" >
      <colour1>
        <colour>
          <hex hexcode="1fc01f"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="47e847"/>
        </colour>
      </colour2>
      <bigShape leftStyle="straight" rightStyle="straight"/>
    </region>
    <region start="2" end="34" label="HEAT" >
      <colour1>
        <colour>
          <hex hexcode="1fc01f"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="47e847"/>
        </colour>
      </colour2>
      <bigShape leftStyle="straight" rightStyle="straight"/>
    </region>
    <region start="44" end="79" label="HEAT" >
      <colour1>
        <colour>
          <hex hexcode="ff66ff"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="ffffff"/>
        </colour>
      </colour2>
      <bigShape leftStyle="straight" rightStyle="straight"/>
    </region>
  </sequence>
</image>

=== ProteinsWebTeam/Pfam/trunk/iPfamWeb/root/static/images/help/seqDomain.xml
<?xml version="1.0" encoding="UTF-8"?>
<image xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" format="png" layout="continuous" scale_x="0.5" scale_y="1.0">
    <sequence length="400" display_data="test all drawing features" name="TestSeq">
        <region start="40" end="200" label="DomainName">
            <colour1>
                <colour><hex hexcode="9999ff"/></colour>
            </colour1>
            <colour2>
                <colour><hex hexcode="99ccff"/></colour>
            </colour2>
            <bigShape leftStyle="curved" rightStyle="curved"/>
        </region>
        <region start="210" end="250" label="FamilyNoNameDisply" link_URL="/">
            <colour1>
                <colour><hex hexcode="339999"/></colour>
            </colour1>
            <colour2>
                <colour><RGB R="51" G="204" B="204"/></colour>
            </colour2>
            <bigShape leftStyle="curved" rightStyle="curved"/>
        </region>
    </sequence>
</image>

=== ProteinsWebTeam/Pfam/trunk/PfamWeb/root/static/images/help/arrows.xml
<?xml version="1.0" encoding="UTF-8"?>
<image xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" format="png" layout="continuous" scale_x="0.5" scale_y="1.0">
    <sequence length="200" name="Arrows">
        <markup start="100" v_align="bottom" label="bold line, uparrow">
            <line style="dashed">
                <colour><hex hexcode="9900CC"/></colour>
            </line>
            <head style="arrow">
                <colour><hex hexcode="9900CC"/></colour>
            </head>
        </markup>
        <markup start="50" v_align="top" label="bold line, down arrow">
            <line style="bold">
                <colour><hex hexcode="707070"/></colour>
            </line>
            <head style="arrow">
                <colour><hex hexcode="707070"/></colour>
            </head>
        </markup>
				<markup start="150" v_align="top" label="bold line, down arrow, mixed colours">
            <line style="bold">
                <colour><hex hexcode="CC0000"/></colour>
            </line>
            <head style="arrow">
                <colour><hex hexcode="33FF66"/></colour>
            </head>
        </markup>
    </sequence>
</image>

=== ProteinsWebTeam/Pfam/trunk/PfamWeb/root/static/images/help/motifs.xml
<?xml version="1.0"?>
<image xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" layout="continuous" format="png" scale_x="0.5" scale_y="1">
  <sequence name="Motifs" length="200">
		<region start="1" end="27" label="Signal Peptide" link_URL="http://www.sanger.ac.uk/Software/Pfam/help/region_help.shtml">
      <colour1>
        <colour>
          <hex hexcode="FF9C00"/>
        </colour>
      </colour1>
      <smlShape/>
    </region>
    <region start="39" end="47" label="Low Complexity" link_URL="http://www.sanger.ac.uk/Software/Pfam/help/region_help.shtml">
      <colour1>
        <colour>
          <hex hexcode="00FFFF"/>
        </colour>
      </colour1>
      <smlShape/>
    </region>
    <region start="67" end="76" label="Low Complexity" link_URL="http://www.sanger.ac.uk/Software/Pfam/help/region_help.shtml">
      <colour1>
        <colour>
          <hex hexcode="00FFFF"/>
        </colour>
      </colour1>
      <smlShape/>
    </region>
    <region start="103" end="123" label="Coiled Coil">
      <colour1>
        <colour>
          <hex hexcode="9CFF00"/>
        </colour>
      </colour1>
      <smlShape/>
    </region>
    <region start="155" end="177" label="Transmembrane" link_URL="http://www.sanger.ac.uk/Software/Pfam/help/region_help.shtml">
      <colour1>
        <colour>
          <hex hexcode="FF0000"/>
        </colour>
      </colour1>
      <smlShape/>
    </region>
    <region start="180" end="195" label="Transmembrane" link_URL="http://www.sanger.ac.uk/Software/Pfam/help/region_help.shtml">
      <colour1>
        <colour>
          <hex hexcode="FF0000"/>
        </colour>
      </colour1>
      <smlShape/>
    </region>
  </sequence>
</image>

=== ProteinsWebTeam/Pfam/trunk/PfamWeb/root/static/images/help/nested.xml
<?xml version="1.0"?>
<image xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" layout="continuous" format="png" scale_x="0.5" scale_y="1">
  <sequence name="Nested" length="200">
    <region start="5" end="80" label="IMPDH" link_URL="/">
      <colour1>
        <colour>
          <hex hexcode="1fc01f"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="47e847"/>
        </colour>
      </colour2>
      <bigShape leftStyle="curved" rightStyle="jagged"/>
    </region>
    <region start="81" end="135" label="CBS" link_URL="/cgi-bin/Pfam/getacc?PF00571">
      <colour1>
        <colour>
          <hex hexcode="c00f0f"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="e83737"/>
        </colour>
      </colour2>
      <bigShape leftStyle="curved" rightStyle="curved"/>
    </region>
    <region start="136" end="197" label="IMPDH" link_URL="/cgi-bin/Pfam/getacc?PF00478">
      <colour1>
        <colour>
          <hex hexcode="1fc01f"/>
        </colour>
      </colour1>
      <colour2>
        <colour>
          <hex hexcode="47e847"/>
        </colour>
      </colour2>
      <bigShape leftStyle="jagged" rightStyle="curved"/>
    </region>
    <markup start="79" end="136" v_align="top" label="Discontinuous domain">
      <line style="mixed">
        <colour>
          <hex hexcode="333333"/>
        </colour>
      </line>
    </markup>
  </sequence>
</image>
