=== ProteinsWebTeam/Pfam/trunk/PfamWeb/root/static/documents/pfamDomainGraphics.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd"
    targetNamespace="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.1">
    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sequence" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="format" default="png">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="png"/>
                        <xs:enumeration value="jpg"/>
                        <xs:enumeration value="gif"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="layout" default="continuous">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="continuous"/>
                        <xs:enumeration value="dicontinuous"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="scale_x" type="xs:float" default="1.0"/>
            <xs:attribute name="scale_y" type="xs:float" default="1.0"/>
            
        </xs:complexType>
    </xs:element>
    
    <xs:element name="sequence">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="region" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="markup" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="length" type="xs:integer"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="display_data" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="region">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="colour1" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="colour"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="colour2" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="colour"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:choice>
                    <xs:element name="bigShape">
                        <xs:complexType>
                            <xs:attribute name="leftStyle" default="curved">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="straight"/>
                                        <xs:enumeration value="jagged"/>
                                        <xs:enumeration value="curved"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="rightStyle" default="curved">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="straight"/>
                                        <xs:enumeration value="jagged"/>
                                        <xs:enumeration value="curved"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="medShape"/>
                    <xs:element name="smlShape"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="start" type="xs:integer"/>
            <xs:attribute name="end" type="xs:integer"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="link_URL" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="colour">
        <xs:complexType>
            <xs:choice>
                <xs:element name="hex">
                    <xs:complexType>
                        <xs:attribute name="hexcode" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="RGB">
                    <xs:complexType>
                        <xs:attribute name="R" type="xs:integer"/>
                        <xs:attribute name="G" type="xs:integer"/>
                        <xs:attribute name="B" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="markup">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="line" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="colour"/>
                        </xs:sequence>
                        <xs:attribute name="style" default="bold">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="bold"/>
                                    <xs:enumeration value="dashed"/>
				    <xs:enumeration value="mixed"/>	
				    <xs:enumeration value="straight"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="head" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="colour"/>
                        </xs:sequence>
                        <xs:attribute name="style" default="diamond">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="circle"/>
                                    <xs:enumeration value="square"/>
			            <xs:enumeration value="diamond"/>
			            <xs:enumeration value="arrow"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="start" type="xs:integer"/>
            <xs:attribute name="end" type="xs:integer"/>
            <xs:attribute name="label" type="xs:string"/>    
            <xs:attribute name="v_align" default="bottom">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="bottom"/>
                        <xs:enumeration value="top"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ProteinsWebTeam/Pfam/trunk/iPfamWeb/root/static/images/help/partial.xml
<?xml version="1.0" encoding="UTF-8"?>
<image xmlns="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd http://www.sanger.ac.uk/Software/Pfam/xml/pfamDomainGraphics.xsd" format="png" layout="continuous" scale_x="0.5" scale_y="1.0">
    <sequence length="400" name="Partial">
        <region start="10" end="110" label="PartN" link_URL="/">
            <colour1>
                <colour><hex hexcode="9999ff"/></colour>
            </colour1>
            <colour2>
                <colour><hex hexcode="99ccff"/></colour>
            </colour2>
            <bigShape leftStyle="jagged" rightStyle="curved"/>
        </region>
        <region start="210" end="350" label="PartC" link_URL="/">
            <colour1>
                <colour><hex hexcode="339999"/></colour>
            </colour1>
            <colour2>
                <colour><RGB R="51" G="204" B="204"/></colour>
            </colour2>
            <bigShape leftStyle="curved" rightStyle="jagged"/>
        </region>
				 <region start="115" end="200" label="PartN_C" link_URL="/">
            <colour1>
       			 <colour>
         			<hex hexcode="1fc01f"/>
        		</colour>
      			</colour1>
      			<colour2>
        			<colour>
          			<hex hexcode="47e847"/>
        			</colour>
      			</colour2>
            <bigShape leftStyle="jagged" rightStyle="jagged"/>
        </region>
    </sequence>
</image>
